services:
  
  mysql-db:
    image: mysql:8.0.18
    container_name: CHAT_APP_MYSQL
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /chat-system-app/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE="chat-app"
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_USER=chat_user
      - MYSQL_PASSWORD=123
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 5s
      retries: 3
  

  redis-db:
    image: redis:latest
    container_name: CHAT_APP_REDIS
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 5s
      retries: 3
    volumes:
      - /chat-system-app/redis:/data


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: CHAT_APP_ELASTICSEARCH
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      xpack.security.http.ssl.enabled: false
      xpack.security.authc.api_key.enabled: false


  main-chat-app:
    build:
      context: ./chat-app
    container_name: CHAT_APP_RAILS
    ports:
      - "3000:3000"
    command: >
      bash -c "./bin/rails db:create && ./bin/rails db:migrate && ./bin/rails server -b 0.0.0.0"
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      MYSQL_DATABASE_USERNAME: root
      MYSQL_DATABASE_PASSWORD: 123
      MYSQL_DATABASE_NAME: chat-app
      MYSQL_DATABASE_HOST: mysql-db
      MYSQL_DATABASE_PORT: 3306
      RAILS_MAX_THREADS: 5
      RAILS_ENV: development
      ELASTICSEARCH_HOST: "http://elasticsearch:9200"
      REDIS_HOST: "redis-db"
      REDIS_PORT: 6379
      REDIS_DB: 0  

  rails-sidekiq:
    build:
      context: ./chat-app
    container_name: CHAT_APP_SIDEKIQ
    command: bundle exec sidekiq
    depends_on:
      mysql-db:
        condition: service_healthy
      redis-db:
        condition: service_healthy
    environment:
      MYSQL_DATABASE_USERNAME: root
      MYSQL_DATABASE_PASSWORD: 123
      MYSQL_DATABASE_NAME: chat-app
      MYSQL_DATABASE_HOST: mysql-db
      MYSQL_DATABASE_PORT: 3306
      RAILS_MAX_THREADS: 5
      RAILS_ENV: development
      ELASTICSEARCH_HOST: "http://elasticsearch:9200"
      REDIS_HOST: "redis-db"
      REDIS_PORT: 6379
      REDIS_DB: 0

  go-creation-app:
    build:
      context: ./chat-app-creation
    container_name: CHAT_APP_GO
    ports:
      - "8080:8080"
    depends_on:
      mysql-db:
        condition: service_healthy
      redis-db:
        condition: service_healthy
    environment:
      MYSQL_HOST: "mysql-db"
      REDIS_HOST: "redis-db:6379"


  nginx-reverse-proxy:
    image: nginx:latest
    container_name: CHAT_APP_NGINX_REVERSE_PROXY
    ports:
      - "8000:80"
    volumes:
      - ./nginx:/etc/nginx
    depends_on:
      mysql-db:
        condition: service_healthy
